---
# Monitoring and Backup Setup Tasks

- name: Create monitoring scripts directory
  file:
    path: "{{ base_dir }}/scripts"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: '0755'

- name: Create health monitoring script
  template:
    src: ../templates/health-monitor.sh.j2
    dest: "{{ base_dir }}/scripts/health-monitor.sh"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: '0755'

- name: Create performance monitoring script
  template:
    src: ../templates/performance-monitor.sh.j2
    dest: "{{ base_dir }}/scripts/performance-monitor.sh"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: '0755'

- name: Create backup script
  template:
    src: ../templates/backup.sh.j2
    dest: "{{ base_dir }}/scripts/backup.sh"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: '0755'

- name: Create log rotation configuration
  copy:
    content: |
      {{ logs_dir }}/*.log {
          daily
          missingok
          rotate {{ monitoring.log_retention_days }}
          compress
          delaycompress
          notifempty
          create 644 {{ system_user }} {{ system_group }}
          postrotate
              systemctl restart drs-validation > /dev/null 2>&1 || true
          endscript
      }
      
      {{ base_dir }}/scripts/*.log {
          weekly
          missingok
          rotate 4
          compress
          delaycompress
          notifempty
          create 644 {{ system_user }} {{ system_group }}
      }
    dest: /etc/logrotate.d/drs-validation
    mode: '0644'

- name: Set up cron jobs for monitoring
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day | default('*') }}"
    job: "{{ item.job }}"
    user: "{{ system_user }}"
  loop:
    - name: "DRS Health Check"
      minute: "*/5"
      hour: "*"
      job: "{{ base_dir }}/scripts/health-monitor.sh"
    - name: "DRS Performance Monitor"
      minute: "*/10"
      hour: "*"
      job: "{{ base_dir }}/scripts/performance-monitor.sh"
    - name: "DRS Daily Backup"
      minute: "0"
      hour: "{{ monitoring.backup_time.split(':')[0] }}"
      job: "{{ base_dir }}/scripts/backup.sh"

- name: Create monitoring log files
  file:
    path: "{{ item }}"
    state: touch
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: '0644'
  loop:
    - "{{ logs_dir }}/health-monitor.log"
    - "{{ logs_dir }}/performance-monitor.log"
    - "{{ logs_dir }}/backup.log"

- name: Test health monitoring script
  command: "{{ base_dir }}/scripts/health-monitor.sh --test"
  become_user: "{{ system_user }}"
  register: health_test_result
  changed_when: false

- name: Display monitoring setup results
  debug:
    msg: |
      Monitoring and backup setup completed:
      - Health monitoring: Every 5 minutes
      - Performance monitoring: Every 10 minutes  
      - Backup schedule: Daily at {{ monitoring.backup_time }}
      - Log rotation: {{ monitoring.log_retention_days }} days
      - Health test result: {{ 'PASSED' if health_test_result.rc == 0 else 'FAILED' }}