---
# Security Configuration Tasks

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: restart ssh
  when: security.disable_root_login

- name: Configure SSH key-only authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
    - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
  notify: restart ssh
  when: security.ssh_key_only

- name: Set secure permissions on DRS directories
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    recurse: "{{ item.recurse | default(false) }}"
  loop:
    - { path: "{{ base_dir }}", mode: '0755' }
    - { path: "{{ app_dir }}", mode: '0755', recurse: true }
    - { path: "{{ logs_dir }}", mode: '0755' }
    - { path: "{{ data_dir }}", mode: '0755' }
    - { path: "{{ backup_dir }}", mode: '0750' }
    - { path: "{{ app_dir }}/.env", mode: '0600' }

- name: Configure system audit for DRS directories
  lineinfile:
    path: /etc/audit/audit.rules
    line: "{{ item }}"
    create: true
  loop:
    - "-w {{ base_dir }} -p wa -k drs_access"
    - "-w {{ app_dir }}/.env -p wa -k drs_env"
  when: ansible_service_mgr == "systemd"
  ignore_errors: true

- name: Display security configuration results
  debug:
    msg: |
      Security configuration completed:
      - SSH hardening: {{ security.ssh_key_only }}
      - Root login disabled: {{ security.disable_root_login }}
      - Directory permissions secured