---
# System Preparation Tasks
# Updates system, installs dependencies, creates users

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_update_result

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: true
    autoclean: true
  register: apt_upgrade_result

- name: Install essential system packages
  apt:
    name:
      - curl
      - wget
      - git
      - htop
      - net-tools
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3
      - python3-pip
    state: present

- name: Create DRS system group
  group:
    name: "{{ system_group }}"
    state: present

- name: Create DRS system user
  user:
    name: "{{ system_user }}"
    group: "{{ system_group }}"
    home: "{{ base_dir }}"
    shell: /bin/bash
    system: true
    create_home: true
    state: present

- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: '0755'
  loop:
    - "{{ base_dir }}"
    - "{{ app_dir }}"
    - "{{ logs_dir }}"
    - "{{ data_dir }}"
    - "{{ backup_dir }}"
    - "{{ config_dir }}"

- name: Set system timezone
  timezone:
    name: America/Argentina/Buenos_Aires

- name: Configure system limits
  pam_limits:
    domain: "{{ system_user }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  loop:
    - { type: 'soft', item: 'nofile', value: '65536' }
    - { type: 'hard', item: 'nofile', value: '65536' }
    - { type: 'soft', item: 'nproc', value: '4096' }
    - { type: 'hard', item: 'nproc', value: '4096' }

- name: Optimize system sysctl parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { name: 'vm.swappiness', value: '10' }
    - { name: 'net.core.rmem_max', value: '16777216' }
    - { name: 'net.core.wmem_max', value: '16777216' }
    - { name: 'net.ipv4.tcp_rmem', value: '4096 12582912 16777216' }
    - { name: 'net.ipv4.tcp_wmem', value: '4096 12582912 16777216' }

- name: Display system preparation results
  debug:
    msg: |
      System preparation completed:
      - Packages updated: {{ apt_upgrade_result.changed }}
      - User created: {{ system_user }}
      - Directories created: {{ base_dir }}
      - System optimized for DRS workload